export const seedData = {
  session: {
    user: "PMED Reviewer",
    role: "PMED/PIPS Reviewer",
  },
  users: [
    { id: "USR-001", name: "System Admin", role: "System Admin", office: "RICT" },
    { id: "USR-002", name: "PMED Reviewer", role: "PMED/PIPS Reviewer", office: "PMED" },
    { id: "USR-003", name: "Rice Encoder", role: "Program Encoder", office: "Rice Program" },
    { id: "USR-004", name: "Budget Reviewer", role: "Budget Reviewer", office: "Budget Division" },
    { id: "USR-005", name: "Management Viewer", role: "Management Viewer", office: "ORD" },
  ],
  masterData: {
    provinces: ["Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino"],
    districts: ["Batanes Lone District", "Cagayan 1st District", "Cagayan 2nd District", "Cagayan 3rd District", "Isabela 1st District", "Isabela 2nd District", "Isabela 3rd District", "Isabela 4th District", "Isabela 5th District", "Isabela 6th District", "Nueva Vizcaya Lone District", "Quirino Lone District"],
    municipalities: [
      { name: "Tuguegarao City", province: "Cagayan", district: "Cagayan 3rd District", psgc: "021529000" },
      { name: "Aparri", province: "Cagayan", district: "Cagayan 1st District", psgc: "021502000" },
      { name: "Ilagan City", province: "Isabela", district: "Isabela 1st District", psgc: "023114000" },
      { name: "Cauayan City", province: "Isabela", district: "Isabela 6th District", psgc: "023108000" },
      { name: "Bayombong", province: "Nueva Vizcaya", district: "Nueva Vizcaya Lone District", psgc: "025002000" },
      { name: "Cabarroguis", province: "Quirino", district: "Quirino Lone District", psgc: "025702000" },
    ],
    offices: ["PMED", "Rice Program", "Corn Program", "HVCDP", "Livestock Program", "FMRDP", "Organic Agriculture Program", "Budget Division"],
    mfos: [
      { code: "MFO 1", name: "Agriculture and Fishery Policy Services", parent_mfo: "" },
      { code: "MFO 2.1", name: "Production Support Services", parent_mfo: "MFO 2" },
      { code: "MFO 2.2", name: "Market Development Services", parent_mfo: "MFO 2" },
      { code: "MFO 2.3", name: "Extension Support, Education and Training Services", parent_mfo: "MFO 2" },
      { code: "MFO 2.4", name: "Research and Development Services", parent_mfo: "MFO 2" },
      { code: "MFO 3", name: "Irrigation Network Services", parent_mfo: "" },
      { code: "MFO 4", name: "Farm-to-Market Road Network Services", parent_mfo: "" },
      { code: "MFO 5", name: "Agricultural and Fishery Machinery, Equipment and Facilities Support Services", parent_mfo: "" },
      { code: "MFO 6", name: "Agriculture and Fishery Regulation Services", parent_mfo: "" },
      { code: "MFO 7", name: "Credit Support Services", parent_mfo: "" },
    ],
    programs: [
      { name: "Rice", paps: ["Production Support Services", "Extension Support, Education and Training Services"], uacs: "310100100001000" },
      { name: "Corn", paps: ["Corn Production Support Services", "Corn Market Development Services"], uacs: "310100100002000" },
      { name: "HVCDP", paps: ["High Value Crops Development Program"], uacs: "310100100003000" },
      { name: "FMRDP", paps: ["Farm-to-Market Road Development Program"], uacs: "310200100001000" },
      { name: "Livestock", paps: ["Livestock Production Support Services"], uacs: "310100100004000" },
    ],
    commodities: ["Rice", "Yellow Corn", "White Corn", "Vegetables", "Coffee", "Cacao", "Cattle", "FMR"],
    interventionTypes: ["Production support", "Extension/training", "Infrastructure", "Machinery/equipment", "Market development", "Enterprise support"],
    unitsOfMeasure: ["number", "percent", "Philippine Peso", "kilograms", "pieces", "number of doses", "hectares", "kilometers", "metric tons", "number of copies", "number of times aired", "number of projects"],
    indicators: [
      { name: "number of beneficiaries provided with production support services", unit: "number", mfo: "Production Support Services", pi_level: "OPIF level" },
      { name: "seeds distributed", unit: "kilograms", mfo: "Production Support Services", pi_level: "Input level" },
      { name: "planting materials distributed", unit: "kilograms, or pieces", mfo: "Production Support Services", pi_level: "Input level" },
      { name: "Farmers/fisherfolk served", unit: "number", mfo: "Production Support Services", pi_level: "OPIF level" },
      { name: "Road length improved", unit: "kilometers", mfo: "Farm-to-Market Road Network Services", pi_level: "OPIF level" },
      { name: "trainings conducted", unit: "number", mfo: "Extension Support, Education and Training Services", pi_level: "Input level" },
    ],
    objectCodes: ["5020301000 - Office Supplies", "5029901000 - Other MOOE", "5060405000 - Roads, Highways and Bridges", "5060406000 - Irrigation Systems", "5060701000 - Agricultural Machinery"],
    expenseClasses: ["PS", "MOOE", "CO", "FinEx"],
    climateTags: ["Not climate tagged", "Climate adaptation", "Climate mitigation", "Climate adaptation and mitigation"],
    gedsiTags: ["Not GEDSI tagged", "Women farmers", "Indigenous peoples", "Youth", "Senior citizens", "Persons with disability"],
  },
  proposals: [
    {
      id: "PBP-2027-0001",
      fiscalYear: "2027",
      title: "Climate-resilient rice seed support for Tuguegarao irrigated clusters",
      description: "Seed and technical assistance package for vulnerable rice clusters.",
      office: "Rice Program",
      program: "Rice",
      subprogram: "National Rice Program",
      pap: "Production Support Services",
      uacs: "310100100001000",
      province: "Cagayan",
      municipality: "Tuguegarao City",
      district: "Cagayan 3rd District",
      commodity: "Rice",
      interventionType: "Production support",
      beneficiaryGroup: "FCAs and individual rice farmers",
      beneficiaries: 1250,
      budgetAmount: 18500000,
      nepAmount: 15000000,
      gaaAmount: 14200000,
      tier: "Tier 2",
      source: "Program workshop",
      justification: "Aligned with FY 2027 PBP guidance on targeted, outcome-based, and shovel-ready interventions.",
      expectedOutput: "Certified seed packages distributed and farmer briefings completed.",
      expectedOutcome: "Improved rice productivity and resilience in priority production areas.",
      readinessStatus: "With DED/POW",
      climateTag: "Climate adaptation",
      climateRationale: "Supports climate-resilient varieties and production timing advisories.",
      gedsiTag: "Women farmers",
      schedule: "Q1-Q4 2027",
      remarks: "Derived from district proposal workbook structure.",
      phase: "Proposal",
      validationStatus: "Validated",
      budgetLines: [
        { id: "BL-001", objectCode: "5029901000 - Other MOOE", expenseClass: "MOOE", amount: 13500000 },
        { id: "BL-002", objectCode: "5060701000 - Agricultural Machinery", expenseClass: "CO", amount: 5000000 },
      ],
      physicalTargets: [
        { id: "PT-001", indicator: "Farmers/fisherfolk served", target: 1250, unit: "individuals" },
        { id: "PT-002", indicator: "Area planted/served", target: 840, unit: "hectares" },
      ],
      created_at: "2026-05-20T09:00:00+08:00",
      updated_at: "2026-05-22T13:30:00+08:00",
      created_by: "Rice Encoder",
      updated_by: "PMED Reviewer",
    },
    {
      id: "PBP-2027-0002",
      fiscalYear: "2027",
      title: "Aparri farm-to-market road completion package",
      description: "FMR segment completion for production-to-market linkage.",
      office: "FMRDP",
      program: "FMRDP",
      subprogram: "Farm-to-Market Road Development",
      pap: "Farm-to-Market Road Development Program",
      uacs: "310200100001000",
      province: "Cagayan",
      municipality: "Aparri",
      district: "Cagayan 1st District",
      commodity: "FMR",
      interventionType: "Infrastructure",
      beneficiaryGroup: "Rice and corn producer groups",
      beneficiaries: 4200,
      budgetAmount: 72000000,
      nepAmount: 65000000,
      gaaAmount: 60000000,
      tier: "Tier 2",
      source: "Congressional request",
      justification: "Supports market access and responds to FMR PBP FY 2027 reference requirements.",
      expectedOutput: "Road segment completed and turned over.",
      expectedOutcome: "Reduced hauling time and improved commodity market access.",
      readinessStatus: "Shovel-ready",
      climateTag: "Not climate tagged",
      climateRationale: "",
      gedsiTag: "Not GEDSI tagged",
      schedule: "Q2-Q4 2027",
      remarks: "Requires DED/POW and right-of-way MOV.",
      phase: "NEP",
      validationStatus: "Approved",
      budgetLines: [{ id: "BL-003", objectCode: "5060405000 - Roads, Highways and Bridges", expenseClass: "CO", amount: 72000000 }],
      physicalTargets: [{ id: "PT-003", indicator: "Road length improved", target: 3.8, unit: "kilometers" }],
      created_at: "2026-05-19T10:00:00+08:00",
      updated_at: "2026-05-22T15:10:00+08:00",
      created_by: "Program Encoder",
      updated_by: "Budget Reviewer",
    },
    {
      id: "PBP-2027-0003",
      fiscalYear: "2027",
      title: "Coffee enterprise support for Bayombong women-led FCA",
      description: "Postharvest and enterprise training support.",
      office: "HVCDP",
      program: "HVCDP",
      subprogram: "High Value Crops",
      pap: "High Value Crops Development Program",
      uacs: "310100100003000",
      province: "Nueva Vizcaya",
      municipality: "Bayombong",
      district: "Nueva Vizcaya Lone District",
      commodity: "Coffee",
      interventionType: "Enterprise support",
      beneficiaryGroup: "Women-led FCA",
      beneficiaries: 320,
      budgetAmount: 9400000,
      nepAmount: 8600000,
      gaaAmount: 8600000,
      tier: "Tier 1",
      source: "RDC",
      justification: "Supports commodity-based enterprise development.",
      expectedOutput: "Equipment, enterprise coaching, and market matching delivered.",
      expectedOutcome: "Higher producer income and women-led enterprise readiness.",
      readinessStatus: "For validation",
      climateTag: "Climate mitigation",
      climateRationale: "",
      gedsiTag: "Women farmers",
      schedule: "Q1-Q3 2027",
      remarks: "Climate rationale intentionally blank for validation demo.",
      phase: "GAA",
      validationStatus: "Needs Correction",
      budgetLines: [{ id: "BL-004", objectCode: "5029901000 - Other MOOE", expenseClass: "MOOE", amount: 9400000 }],
      physicalTargets: [{ id: "PT-004", indicator: "Groups assisted", target: 6, unit: "groups" }],
      created_at: "2026-05-18T08:45:00+08:00",
      updated_at: "2026-05-21T11:20:00+08:00",
      created_by: "HVCDP Encoder",
      updated_by: "PMED Reviewer",
    },
  ],
  phaseHistory: [
    { proposalId: "PBP-2027-0001", phase: "Proposal", date: "2026-05-20", budgetAmount: 18500000, physicalTarget: 1250, editor: "Rice Encoder", remarks: "Initial encoded proposal." },
    { proposalId: "PBP-2027-0001", phase: "NEP", date: "2026-09-15", budgetAmount: 15000000, physicalTarget: 1050, editor: "Budget Reviewer", remarks: "Reduced during NEP consolidation." },
    { proposalId: "PBP-2027-0001", phase: "GAA", date: "2026-12-20", budgetAmount: 14200000, physicalTarget: 1000, editor: "Budget Reviewer", remarks: "GAA level recorded." },
    { proposalId: "PBP-2027-0001", phase: "BED", date: "2027-01-15", budgetAmount: 14200000, physicalTarget: 1000, editor: "PMED Reviewer", remarks: "BED No. 2 target locked." },
  ],
  attachments: [
    { id: "ATT-001", proposalId: "PBP-2027-0001", type: "Readiness document", name: "Supplier list and beneficiary registry", driveUrl: "https://drive.google.com/example/seed-support", uploaded_by: "Rice Encoder" },
    { id: "ATT-002", proposalId: "PBP-2027-0002", type: "DED/POW", name: "Aparri FMR DED and POW", driveUrl: "https://drive.google.com/example/fmr-ded", uploaded_by: "FMRDP Encoder" },
  ],
  bulkSubmissions: [
    {
      id: "BULK-0001",
      fiscalYear: "2027",
      program: "Rice",
      office: "Rice Program",
      templateCode: "BULK-COMMODITY",
      phase: "Proposal",
      sourceFile: "1st District Cagayan 2027 Proposal.xlsx",
      status: "Validated",
      submitted_at: "2026-05-22T09:10:00+08:00",
      submitted_by: "Rice Encoder",
      remarks: "Imported from banner-program district workbook.",
      created_at: "2026-05-22T09:10:00+08:00",
      updated_at: "2026-05-22T10:00:00+08:00",
      created_by: "Rice Encoder",
      updated_by: "PMED Reviewer",
    },
    {
      id: "BULK-0002",
      fiscalYear: "2027",
      program: "FMRDP",
      office: "FMRDP",
      templateCode: "BULK-FMR",
      phase: "Proposal",
      sourceFile: "FMR PBP FY 2027.xlsx",
      status: "Needs Correction",
      submitted_at: "2026-05-22T14:05:00+08:00",
      submitted_by: "Program Encoder",
      remarks: "Pending municipality and estimated amount checks.",
      created_at: "2026-05-22T14:05:00+08:00",
      updated_at: "2026-05-22T14:25:00+08:00",
      created_by: "Program Encoder",
      updated_by: "PMED Reviewer",
    },
  ],
  bulkTemplates: [
    {
      code: "BULK-RFO2-SPATIAL",
      name: "RFO2 spatial budget forum workbook",
      description: "Imports regional spatial targeting rows where multiple banner programs and multiple DA operating units/offices are mixed in one workbook.",
      expectedSheets: ["BY INTERVENTION", "BY COMMODITY or INDUSTRY"],
      requiredColumns: ["Region", "Province", "City/ Municipality", "DA Operating Unit / Agency with Corresponding FY 2027 Proposal"],
      importMode: "Google Drive upload, convert to Google Sheets, detect program and office per row, stage intervention/commodity rows for review",
      sourceBasis: "C:/Users/Jeff Factora/Downloads/2027/PIP/RFO2 Budget Forum/RFO2_Spatial_Details_of_FY_2027_Budget_FINAL.xlsx",
      allowsMultiplePrograms: true,
      allowsMultipleOffices: true,
      programDetection: "Use DA Operating Unit / Agency and Inferred Commodity/Industry columns",
    },
    {
      code: "BULK-COMMODITY",
      name: "Commodity banner program proposal workbook",
      description: "Imports intervention or proposal rows from Rice, Corn, HVCDP, NUPAP, Livestock, OAP, Halal, NSHP, and similar banner sheets.",
      expectedSheets: ["RICE", "CORN", "HVCDP", "NUPAP", "LIVESTOCK", "OAP"],
      requiredColumns: ["PROGRAM/SUBPROGRAM/ INDICATORS", "UNIT OF MEASURE", "FY 2027 PROPOSAL", "Remarks (Breakdown of Municipality Target for FY 2027 )"],
      importMode: "Google Drive upload, convert to Google Sheets, extract rows by configured sheet profile",
      sourceBasis: "source-files/sample-excel-files/* District * 2027*.xlsx",
    },
    {
      code: "BULK-FMR",
      name: "FMR / infrastructure proposal workbook",
      description: "Imports project rows with municipality, barangay/location, project name, estimated length, and amount.",
      expectedSheets: ["FMR", "PRDP"],
      requiredColumns: ["MUNICIPALITY", "LOCATION (BARANGAY)", "NAME OF PROJECTS", "ESTIMATED LENGTH (KM)", "ESTIMATED AMOUNT"],
      importMode: "Google Drive upload, convert to Google Sheets, extract project rows into proposals and physical targets",
      sourceBasis: "source-files/sample-excel-files/* District * 2027*.xlsx and source-files/powerpoint-references/FMR PBP FY 2027.pptx",
    },
    {
      code: "BULK-BED-CAPTURE",
      name: "BED financial and physical capture workbook",
      description: "Imports BED 1 obligation, BED 2 physical, and BED 3 disbursement values without overwriting earlier phase snapshots.",
      expectedSheets: ["FINANCIAL CAPTURE SHEET", "PHYSICAL CAPTURE SHEET", "BED 1 GENERATED", "BED 2 GENERATED", "BED 3 GENERATED"],
      requiredColumns: ["PRPOPOSAL/BEDS", "OU", "PREXC PROGRAM", "PREXC SUB-PROGRAM", "ACTIVITY", "MONTH", "QUARTER", "MOOE (Php '000)", "CO (Php '000)", "TOTAL (Php '000)"],
      importMode: "Google Drive upload, convert to Google Sheets, append phase_history and BED budget/target rows",
      sourceBasis: "source-files/GAA-BED-forms/CORN BED 2.xlsx and source-files/GAA-BED-forms/RICE BED 2.xlsx",
    },
  ],
  templates: [
    { code: "BP-A", name: "Program budget matrix", sourceFile: "source-files/budget-guidelines/NATIONAL-BUDGET-MEMORANDUM-NO.-153_updated BUDGET CALL.pdf", phase: "Reporting", outputFormat: "CSV/XLSX" },
    { code: "BP-B", name: "Performance measures", sourceFile: "source-files/sample-excel-files/* District * 2027*.xlsx", phase: "Reporting", outputFormat: "CSV/XLSX" },
    { code: "BP-C-RDC", name: "RDC proposal inputs", sourceFile: "source-files/pdf-references/4. Regional Development Councils (RDCs) Process During Budget Preparation.pptx", phase: "Proposal/Reporting", outputFormat: "CSV/XLSX" },
    { code: "BP-D-CSO", name: "CSO consultation inputs", sourceFile: "source-files/budget-guidelines/NATIONAL-BUDGET-MEMORANDUM-NO.-153_updated BUDGET CALL.pdf", phase: "Proposal/Reporting", outputFormat: "CSV/XLSX" },
    { code: "BP-202", name: "Tier 2 Profile", sourceFile: "source-files/NEP-forms/QTR BP FORM 202 signed.pdf", phase: "Proposal/NEP", outputFormat: "CSV/XLSX/PDF" },
    { code: "BP-206", name: "Convergence matrix", sourceFile: "source-files/pdf-references/3. Conduct of Program Convergence Budget (PCB).pptx", phase: "Reporting", outputFormat: "CSV/XLSX" },
    { code: "BP-207", name: "Climate expenditure report", sourceFile: "source-files/budget-guidelines/NATIONAL-BUDGET-MEMORANDUM-NO.-153_updated BUDGET CALL.pdf", phase: "Reporting", outputFormat: "CSV/XLSX" },
    { code: "BED-2", name: "Physical Plan", sourceFile: "source-files/GAA-BED-forms/RICE BED 2.xlsx", phase: "BED", outputFormat: "CSV/XLSX" },
    { code: "DISTRICT-PROPOSAL", name: "District proposal workbook", sourceFile: "source-files/sample-excel-files/* District * 2027*.xlsx", phase: "Proposal", outputFormat: "XLSX import" },
    { code: "BULK-EXCEPTION", name: "Bulk upload exception report", sourceFile: "Generated from bulk_submissions and validation_issues", phase: "Reporting", outputFormat: "CSV/XLSX" },
  ],
};
